dnsdock:
  image: simonqbs/dnsdock
  container_name: dnsdock
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - 172.17.42.1:53:53/udp
  command: -nameserver="8.8.8.8:53" -dns=":53"
mysql:
  image: mysql:5.7
  env_file:
    - ./environment.env
  volumes:
    - ./storage/mysql:/var/lib/mysql
redis:
  image: redis:3.0
  volumes:
    - ./storage/redis:/data
fpm:
  image: zetaron/laravel-php
  volumes:
    - ./api:/var/www/html
  links:
    - mysql
    - redis
  env_file:
    - ./environment.env
web:
  image: zetaron/laravel-web
  volumes:
    - ./api:/var/www/html:ro
  links:
    - fpm
  env_file:
    - ./environment.env
composer:
  image: composer/composer
  volumes:
    - ./api:/app
  env_file:
    - ./environment.env
  command: install
